// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  id, email, display_name, password_hash
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, email, email_verified, display_name, password_hash, totp_secret, totp_enabled, status, created_at, last_login_at, deleted_at
`

type CreateAccountParams struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, email_verified, display_name, password_hash, totp_secret, totp_enabled, status, created_at, last_login_at, deleted_at FROM accounts
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, email_verified, display_name, password_hash, totp_secret, totp_enabled, status, created_at, last_login_at, deleted_at FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE accounts
SET status = 'deleted', deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, id)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts
SET status = $2
WHERE id = $1
RETURNING id, email, email_verified, display_name, password_hash, totp_secret, totp_enabled, status, created_at, last_login_at, deleted_at
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}
