// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components
WHERE entity_id = $1 AND component_type = $2
`

type DeleteComponentParams struct {
	EntityID      pgtype.UUID
	ComponentType string
}

func (q *Queries) DeleteComponent(ctx context.Context, arg DeleteComponentParams) error {
	_, err := q.db.Exec(ctx, deleteComponent, arg.EntityID, arg.ComponentType)
	return err
}

const getComponent = `-- name: GetComponent :one
SELECT entity_id, component_type, state, created_at_tick, updated_at_tick FROM components
WHERE entity_id = $1 AND component_type = $2
`

type GetComponentParams struct {
	EntityID      pgtype.UUID
	ComponentType string
}

func (q *Queries) GetComponent(ctx context.Context, arg GetComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, getComponent, arg.EntityID, arg.ComponentType)
	var i Component
	err := row.Scan(
		&i.EntityID,
		&i.ComponentType,
		&i.State,
		&i.CreatedAtTick,
		&i.UpdatedAtTick,
	)
	return i, err
}

const listEntitiesWithComponent = `-- name: ListEntitiesWithComponent :many
SELECT c.entity_id, c.component_type, c.state, c.created_at_tick, c.updated_at_tick
FROM components c
JOIN entities e ON e.id = c.entity_id
WHERE c.component_type = $1
  AND e.destroyed_at_tick IS NULL
`

// "Find all live entities with component X" — the system-iterates-over-
// inputs pattern. JOINed to entities so we can filter out soft-deleted
// rows; the (component_type, entity_id) index drives the components
// side of the join.
func (q *Queries) ListEntitiesWithComponent(ctx context.Context, componentType string) ([]Component, error) {
	rows, err := q.db.Query(ctx, listEntitiesWithComponent, componentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.EntityID,
			&i.ComponentType,
			&i.State,
			&i.CreatedAtTick,
			&i.UpdatedAtTick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setComponent = `-- name: SetComponent :one
INSERT INTO components (
  entity_id, component_type, state, created_at_tick, updated_at_tick
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (entity_id, component_type) DO UPDATE
SET state = EXCLUDED.state,
    updated_at_tick = EXCLUDED.updated_at_tick
RETURNING entity_id, component_type, state, created_at_tick, updated_at_tick
`

type SetComponentParams struct {
	EntityID      pgtype.UUID
	ComponentType string
	State         []byte
	CreatedAtTick int64
	UpdatedAtTick int64
}

// Upsert keyed on (entity_id, component_type). The PK enforces "one of
// each type per entity," so this is the only sensible write shape.
// created_at_tick survives the ON CONFLICT path (keep the original);
// updated_at_tick is bumped on every write.
func (q *Queries) SetComponent(ctx context.Context, arg SetComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, setComponent,
		arg.EntityID,
		arg.ComponentType,
		arg.State,
		arg.CreatedAtTick,
		arg.UpdatedAtTick,
	)
	var i Component
	err := row.Scan(
		&i.EntityID,
		&i.ComponentType,
		&i.State,
		&i.CreatedAtTick,
		&i.UpdatedAtTick,
	)
	return i, err
}
