// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity_positions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEntityPosition = `-- name: DeleteEntityPosition :exec
DELETE FROM entity_positions
WHERE entity_id = $1
`

// Called when an entity leaves the world: destroyed, moved into a
// container, etc. Position is liveness state; absence of a row means
// "not in the world."
func (q *Queries) DeleteEntityPosition(ctx context.Context, entityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntityPosition, entityID)
	return err
}

const getEntitiesAtPosition = `-- name: GetEntitiesAtPosition :many
SELECT entity_id, region_id, x, y, updated_at_tick FROM entity_positions
WHERE region_id = $1
  AND x = $2
  AND y = $3
`

type GetEntitiesAtPositionParams struct {
	RegionID int32
	X        int32
	Y        int32
}

// Drives "what's at (x,y) in region R" — pickup checks, collision
// detection, click-to-inspect. Uses the (region_id, x, y) composite
// index.
func (q *Queries) GetEntitiesAtPosition(ctx context.Context, arg GetEntitiesAtPositionParams) ([]EntityPosition, error) {
	rows, err := q.db.Query(ctx, getEntitiesAtPosition, arg.RegionID, arg.X, arg.Y)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityPosition{}
	for rows.Next() {
		var i EntityPosition
		if err := rows.Scan(
			&i.EntityID,
			&i.RegionID,
			&i.X,
			&i.Y,
			&i.UpdatedAtTick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesInRegion = `-- name: GetEntitiesInRegion :many
SELECT entity_id, region_id, x, y, updated_at_tick FROM entity_positions
WHERE region_id = $1
`

// Broad scan: all positioned entities in a region. The region
// goroutine uses this when warming its in-memory mirror; gameplay
// code should prefer GetEntitiesAtPosition when possible.
func (q *Queries) GetEntitiesInRegion(ctx context.Context, regionID int32) ([]EntityPosition, error) {
	rows, err := q.db.Query(ctx, getEntitiesInRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityPosition{}
	for rows.Next() {
		var i EntityPosition
		if err := rows.Scan(
			&i.EntityID,
			&i.RegionID,
			&i.X,
			&i.Y,
			&i.UpdatedAtTick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityPosition = `-- name: GetEntityPosition :one
SELECT entity_id, region_id, x, y, updated_at_tick FROM entity_positions
WHERE entity_id = $1
`

func (q *Queries) GetEntityPosition(ctx context.Context, entityID pgtype.UUID) (EntityPosition, error) {
	row := q.db.QueryRow(ctx, getEntityPosition, entityID)
	var i EntityPosition
	err := row.Scan(
		&i.EntityID,
		&i.RegionID,
		&i.X,
		&i.Y,
		&i.UpdatedAtTick,
	)
	return i, err
}

const setEntityPosition = `-- name: SetEntityPosition :one
INSERT INTO entity_positions (
  entity_id, region_id, x, y, updated_at_tick
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (entity_id) DO UPDATE
SET region_id = EXCLUDED.region_id,
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    updated_at_tick = EXCLUDED.updated_at_tick
RETURNING entity_id, region_id, x, y, updated_at_tick
`

type SetEntityPositionParams struct {
	EntityID      pgtype.UUID
	RegionID      int32
	X             int32
	Y             int32
	UpdatedAtTick int64
}

// Upsert: an entity has at most one position. Use this both for "spawn
// this entity at (x,y)" and "this entity just moved." updated_at_tick
// is bumped on every write so the broadcast layer can debounce.
func (q *Queries) SetEntityPosition(ctx context.Context, arg SetEntityPositionParams) (EntityPosition, error) {
	row := q.db.QueryRow(ctx, setEntityPosition,
		arg.EntityID,
		arg.RegionID,
		arg.X,
		arg.Y,
		arg.UpdatedAtTick,
	)
	var i EntityPosition
	err := row.Scan(
		&i.EntityID,
		&i.RegionID,
		&i.X,
		&i.Y,
		&i.UpdatedAtTick,
	)
	return i, err
}
