// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (
  id, season_id, entity_type, created_at_tick
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, season_id, entity_type, created_at_tick, destroyed_at_tick
`

type CreateEntityParams struct {
	ID            pgtype.UUID
	SeasonID      int32
	EntityType    string
	CreatedAtTick int64
}

// Inserts just the entities row. Per-type tables (Layer 3) and the
// entity_positions / components rows are added by the transactional
// helper in Go, not here.
func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.ID,
		arg.SeasonID,
		arg.EntityType,
		arg.CreatedAtTick,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.EntityType,
		&i.CreatedAtTick,
		&i.DestroyedAtTick,
	)
	return i, err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, season_id, entity_type, created_at_tick, destroyed_at_tick FROM entities
WHERE id = $1
`

func (q *Queries) GetEntityByID(ctx context.Context, id pgtype.UUID) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByID, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.EntityType,
		&i.CreatedAtTick,
		&i.DestroyedAtTick,
	)
	return i, err
}

const listEntitiesByTypeInSeason = `-- name: ListEntitiesByTypeInSeason :many
SELECT id, season_id, entity_type, created_at_tick, destroyed_at_tick FROM entities
WHERE season_id = $1
  AND entity_type = $2
  AND destroyed_at_tick IS NULL
`

type ListEntitiesByTypeInSeasonParams struct {
	SeasonID   int32
	EntityType string
}

// "All living characters in season N," "all NPCs in season N," etc.
// Filters out soft-deleted rows so callers don't have to.
func (q *Queries) ListEntitiesByTypeInSeason(ctx context.Context, arg ListEntitiesByTypeInSeasonParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByTypeInSeason, arg.SeasonID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.EntityType,
			&i.CreatedAtTick,
			&i.DestroyedAtTick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEntity = `-- name: SoftDeleteEntity :one
UPDATE entities
SET destroyed_at_tick = $2
WHERE id = $1 AND destroyed_at_tick IS NULL
RETURNING id, season_id, entity_type, created_at_tick, destroyed_at_tick
`

type SoftDeleteEntityParams struct {
	ID              pgtype.UUID
	DestroyedAtTick *int64
}

// Sets destroyed_at_tick. Application code is responsible for also
// deleting the entity_positions row in the same transaction (the
// death/destroy helper does this); we don't cascade on soft-delete
// so the audit log (Layer 6) can still inspect the entity's history.
func (q *Queries) SoftDeleteEntity(ctx context.Context, arg SoftDeleteEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, softDeleteEntity, arg.ID, arg.DestroyedAtTick)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.EntityType,
		&i.CreatedAtTick,
		&i.DestroyedAtTick,
	)
	return i, err
}

const sweepDestroyedEntities = `-- name: SweepDestroyedEntities :execrows
DELETE FROM entities
WHERE destroyed_at_tick IS NOT NULL
  AND destroyed_at_tick < $1
`

// Hard-deletes entities that have been soft-deleted longer than the
// retention window. Cascading FKs (entity_positions, components, etc.)
// carry the deletion through. Returns rows affected so the caller can
// log/alert. Gated by config in the Go wrapper — see DESIGN.md §6.6.
func (q *Queries) SweepDestroyedEntities(ctx context.Context, destroyedAtTick *int64) (int64, error) {
	result, err := q.db.Exec(ctx, sweepDestroyedEntities, destroyedAtTick)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
