// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            pgtype.UUID
	Email         string
	EmailVerified bool
	DisplayName   string
	PasswordHash  string
	TotpSecret    *string
	TotpEnabled   bool
	Status        string
	CreatedAt     pgtype.Timestamptz
	LastLoginAt   pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type AccountFlag struct {
	AccountID pgtype.UUID
	FlagType  string
	FlagValue []byte
	CreatedAt pgtype.Timestamptz
}

type Season struct {
	ID        int32
	Name      *string
	Status    string
	WorldSeed int64
	Modifiers []byte
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	WipedAt   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type SeasonParticipation struct {
	AccountID      pgtype.UUID
	SeasonID       int32
	CharactersMade int32
	Deaths         int32
	DeepestRegion  *int32
	FinalSummary   []byte
}
