// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendModerationAction = `-- name: AppendModerationAction :one
INSERT INTO moderation_actions (
  id, account_id, action_type, reason, details, applied_by, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, account_id, action_type, reason, details, applied_by, applied_at, expires_at
`

type AppendModerationActionParams struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	ActionType string
	Reason     string
	Details    []byte
	AppliedBy  pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
}

// Append-only. Reversing a prior action means inserting a new row
// with action_type='unban'.
func (q *Queries) AppendModerationAction(ctx context.Context, arg AppendModerationActionParams) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, appendModerationAction,
		arg.ID,
		arg.AccountID,
		arg.ActionType,
		arg.Reason,
		arg.Details,
		arg.AppliedBy,
		arg.ExpiresAt,
	)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ActionType,
		&i.Reason,
		&i.Details,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findActiveBansAndSuspensions = `-- name: FindActiveBansAndSuspensions :many
SELECT m.id, m.account_id, m.action_type, m.reason, m.details, m.applied_by, m.applied_at, m.expires_at
FROM moderation_actions m
WHERE m.account_id = $1
  AND m.action_type IN ('ban', 'suspend')
  AND (m.expires_at IS NULL OR m.expires_at > NOW())
  AND NOT EXISTS (
    SELECT 1 FROM moderation_actions u
    WHERE u.account_id = m.account_id
      AND u.action_type = 'unban'
      AND u.applied_at > m.applied_at
  )
ORDER BY m.applied_at DESC
`

// A punitive action is currently in effect for $1 if:
//   - it is a 'ban' or 'suspend' (mute and warn are their own thing),
//   - it has not yet expired (or has no expiry), AND
//   - no later 'unban' action has overturned it.
func (q *Queries) FindActiveBansAndSuspensions(ctx context.Context, accountID pgtype.UUID) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, findActiveBansAndSuspensions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationAction{}
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ActionType,
			&i.Reason,
			&i.Details,
			&i.AppliedBy,
			&i.AppliedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationActionsForAccount = `-- name: ListModerationActionsForAccount :many
SELECT id, account_id, action_type, reason, details, applied_by, applied_at, expires_at FROM moderation_actions
WHERE account_id = $1
ORDER BY applied_at DESC
`

func (q *Queries) ListModerationActionsForAccount(ctx context.Context, accountID pgtype.UUID) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, listModerationActionsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationAction{}
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ActionType,
			&i.Reason,
			&i.Details,
			&i.AppliedBy,
			&i.AppliedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
