// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ping.sql

package sqlc

import (
	"context"
)

const ping = `-- name: Ping :one

SELECT 1::int
`

// Smoke-test query so sqlc generate has something to chew on
// before any real schema lands. Delete when real queries arrive.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
