// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seasons.sql

package sqlc

import (
	"context"
)

const getActiveSeason = `-- name: GetActiveSeason :one
SELECT id, name, status, world_seed, modifiers, starts_at, ends_at, wiped_at, created_at FROM seasons
WHERE status = 'active'
`

func (q *Queries) GetActiveSeason(ctx context.Context) (Season, error) {
	row := q.db.QueryRow(ctx, getActiveSeason)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.WorldSeed,
		&i.Modifiers,
		&i.StartsAt,
		&i.EndsAt,
		&i.WipedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, name, status, world_seed, modifiers, starts_at, ends_at, wiped_at, created_at FROM seasons
WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id int32) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.WorldSeed,
		&i.Modifiers,
		&i.StartsAt,
		&i.EndsAt,
		&i.WipedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSeasonStatus = `-- name: UpdateSeasonStatus :one
UPDATE seasons
SET status = $2
WHERE id = $1
RETURNING id, name, status, world_seed, modifiers, starts_at, ends_at, wiped_at, created_at
`

type UpdateSeasonStatusParams struct {
	ID     int32
	Status string
}

// Caller is responsible for transition validity. The unique partial index
// on (status) WHERE status='active' ensures at most one active season.
func (q *Queries) UpdateSeasonStatus(ctx context.Context, arg UpdateSeasonStatusParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeasonStatus, arg.ID, arg.Status)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.WorldSeed,
		&i.Modifiers,
		&i.StartsAt,
		&i.EndsAt,
		&i.WipedAt,
		&i.CreatedAt,
	)
	return i, err
}
