// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id, account_id, token_hash, ip_address, user_agent, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, account_id, token_hash, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at, revoke_reason
`

type CreateSessionParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash string
	IpAddress *netip.Addr
	UserAgent *string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, account_id, token_hash, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at, revoke_reason FROM sessions
WHERE token_hash = $1
`

// Caller is still responsible for checking expires_at / revoked_at and
// enforcing whatever "valid session" means in the auth layer. This query
// only finds the row.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const listActiveSessionsForAccount = `-- name: ListActiveSessionsForAccount :many
SELECT id, account_id, token_hash, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at, revoke_reason FROM sessions
WHERE account_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsForAccount(ctx context.Context, accountID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked_at = NOW(), revoke_reason = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, account_id, token_hash, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at, revoke_reason
`

type RevokeSessionParams struct {
	ID           pgtype.UUID
	RevokeReason *string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.ID, arg.RevokeReason)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}
