database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: coffee_subscription
  sslmode: disable
  max_conns: 20
  max_idle: 5
  timeout: 10s

server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s

stripe:
  secret_key: sk_test_...
  webhook_secret: whsec_...
  payment_success: https://yoursite.com/payment/success
  payment_cancel: https://yoursite.com/payment/cancel